id: PB44B1B74
initial_creation_type: input
source_metadata:
  title: Geluk Series
  language: en
  description: 'Texts related to the Geluk (dge lugs) School of Tibetan Buddhism:'
  volume:
    ed8f535a83ac4a35b11bfb3052d071e0:
      title: 'Words of Truth: An Aspiration for the Spread of the Noble Gendenpa Tradition'
      parent: Aspiration Prayers
created_at: '2022-03-01T03:41:49.275939'
last_modified_at: '2022-03-01T03:41:49.275944'
